In [1]:
!pip install -U autotrain-advanced

Requirement already satisfied: autotrain-advanced in /usr/local/lib/python3.11/dist-packages (0.8.36)
Requirement already satisfied: albumentations==1.4.23 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.4.23)
Requirement already satisfied: datasets~=3.2.0 in /usr/local/lib/python3.11/dist-packages (from datasets[vision]~=3.2.0->autotrain-advanced) (3.2.0)
Requirement already satisfied: evaluate==0.4.3 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.4.3)
Requirement already satisfied: ipadic==1.0.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.0.0)
Requirement already satisfied: jiwer==3.0.5 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (3.0.5)
Requirement already satisfied: joblib==1.4.2 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.4.2)
Requirement already satisfied: loguru==0.7.3 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.7.3)
Requirement already satisfied: pandas==2.2.3 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (2.2.3)
Requirement already satisfied: nltk==3.9.1 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (3.9.1)
Requirement already satisfied: optuna==4.1.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (4.1.0)
Requirement already satisfied: Pillow==11.0.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (11.0.0)
Requirement already satisfied: sacremoses==0.1.1 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.1.1)
Requirement already satisfied: scikit-learn==1.6.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.6.0)
Requirement already satisfied: sentencepiece==0.2.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.2.0)
Requirement already satisfied: tqdm==4.67.1 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (4.67.1)
Requirement already satisfied: werkzeug==3.1.3 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (3.1.3)
Requirement already satisfied: xgboost==2.1.3 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (2.1.3)
Collecting huggingface-hub==0.27.0 (from autotrain-advanced)
  Using cached huggingface_hub-0.27.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (2.32.3)
Requirement already satisfied: einops==0.8.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.8.0)
Requirement already satisfied: packaging==24.2 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (24.2)
Requirement already satisfied: cryptography==44.0.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (44.0.0)
Requirement already satisfied: nvitop==1.3.2 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.3.2)
Requirement already satisfied: tensorboard==2.18.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (2.18.0)
Requirement already satisfied: peft==0.14.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.14.0)
Requirement already satisfied: trl==0.13.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.13.0)
Requirement already satisfied: tiktoken==0.8.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.8.0)
Requirement already satisfied: transformers==4.48.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (4.48.0)
Requirement already satisfied: accelerate==1.2.1 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.2.1)
Requirement already satisfied: rouge-score==0.1.2 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.1.2)
Requirement already satisfied: py7zr==0.22.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.22.0)
Requirement already satisfied: fastapi==0.115.6 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.115.6)
Requirement already satisfied: uvicorn==0.34.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.34.0)
Requirement already satisfied: python-multipart==0.0.20 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.0.20)
Requirement already satisfied: pydantic==2.10.4 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (2.10.4)
Requirement already satisfied: hf-transfer in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.1.9)
Requirement already satisfied: pyngrok==7.2.1 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (7.2.1)
Requirement already satisfied: authlib==1.4.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.4.0)
Requirement already satisfied: itsdangerous==2.2.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (2.2.0)
Requirement already satisfied: seqeval==1.2.2 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.2.2)
Requirement already satisfied: httpx==0.28.1 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.28.1)
Requirement already satisfied: pyyaml==6.0.2 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (6.0.2)
Requirement already satisfied: timm==1.0.12 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.0.12)
Requirement already satisfied: torchmetrics==1.6.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (1.6.0)
Requirement already satisfied: pycocotools==2.0.8 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (2.0.8)
Requirement already satisfied: sentence-transformers==3.3.1 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (3.3.1)
Requirement already satisfied: bitsandbytes==0.45.0 in /usr/local/lib/python3.11/dist-packages (from autotrain-advanced) (0.45.0)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.11/dist-packages (from accelerate==1.2.1->autotrain-advanced) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate==1.2.1->autotrain-advanced) (5.9.5)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.11/dist-packages (from accelerate==1.2.1->autotrain-advanced) (2.6.0+cu124)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate==1.2.1->autotrain-advanced) (0.5.3)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.11/dist-packages (from albumentations==1.4.23->autotrain-advanced) (1.15.2)
Requirement already satisfied: albucore==0.0.21 in /usr/local/lib/python3.11/dist-packages (from albumentations==1.4.23->autotrain-advanced) (0.0.21)
Requirement already satisfied: eval-type-backport in /usr/local/lib/python3.11/dist-packages (from albumentations==1.4.23->autotrain-advanced) (0.2.2)
Requirement already satisfied: opencv-python-headless>=4.9.0.80 in /usr/local/lib/python3.11/dist-packages (from albumentations==1.4.23->autotrain-advanced) (4.11.0.86)
Requirement already satisfied: typing_extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from bitsandbytes==0.45.0->autotrain-advanced) (4.13.2)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography==44.0.0->autotrain-advanced) (1.17.1)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.3->autotrain-advanced) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.3->autotrain-advanced) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate==0.4.3->autotrain-advanced) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate==0.4.3->autotrain-advanced) (2024.9.0)
Requirement already satisfied: starlette<0.42.0,>=0.40.0 in /usr/local/lib/python3.11/dist-packages (from fastapi==0.115.6->autotrain-advanced) (0.41.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->autotrain-advanced) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->autotrain-advanced) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->autotrain-advanced) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx==0.28.1->autotrain-advanced) (3.10)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub==0.27.0->autotrain-advanced) (3.18.0)
Requirement already satisfied: click<9.0.0,>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from jiwer==3.0.5->autotrain-advanced) (8.1.8)
Requirement already satisfied: rapidfuzz<4,>=3 in /usr/local/lib/python3.11/dist-packages (from jiwer==3.0.5->autotrain-advanced) (3.13.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk==3.9.1->autotrain-advanced) (2024.11.6)
Requirement already satisfied: nvidia-ml-py<12.536.0a0,>=11.450.51 in /usr/local/lib/python3.11/dist-packages (from nvitop==1.3.2->autotrain-advanced) (12.535.161)
Requirement already satisfied: cachetools>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from nvitop==1.3.2->autotrain-advanced) (5.5.2)
Requirement already satisfied: termcolor>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from nvitop==1.3.2->autotrain-advanced) (3.0.1)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from optuna==4.1.0->autotrain-advanced) (1.15.2)
Requirement already satisfied: colorlog in /usr/local/lib/python3.11/dist-packages (from optuna==4.1.0->autotrain-advanced) (6.9.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna==4.1.0->autotrain-advanced) (2.0.40)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas==2.2.3->autotrain-advanced) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.2.3->autotrain-advanced) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas==2.2.3->autotrain-advanced) (2025.2)
Requirement already satisfied: texttable in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (1.7.0)
Requirement already satisfied: pycryptodomex>=3.16.0 in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (3.22.0)
Requirement already satisfied: pyzstd>=0.15.9 in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (0.16.2)
Requirement already satisfied: pyppmd<1.2.0,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (1.1.1)
Requirement already satisfied: pybcj<1.1.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (1.0.6)
Requirement already satisfied: multivolumefile>=0.2.3 in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (0.2.3)
Requirement already satisfied: inflate64<1.1.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (1.0.1)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from py7zr==0.22.0->autotrain-advanced) (1.1.0)
Requirement already satisfied: matplotlib>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from pycocotools==2.0.8->autotrain-advanced) (3.10.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic==2.10.4->autotrain-advanced) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic==2.10.4->autotrain-advanced) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->autotrain-advanced) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests==2.32.3->autotrain-advanced) (2.4.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from rouge-score==0.1.2->autotrain-advanced) (1.4.0)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from rouge-score==0.1.2->autotrain-advanced) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.6.0->autotrain-advanced) (3.6.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.11/dist-packages (from tensorboard==2.18.0->autotrain-advanced) (1.71.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard==2.18.0->autotrain-advanced) (3.8)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.11/dist-packages (from tensorboard==2.18.0->autotrain-advanced) (5.29.4)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard==2.18.0->autotrain-advanced) (75.2.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard==2.18.0->autotrain-advanced) (0.7.2)
Requirement already satisfied: torchvision in /usr/local/lib/python3.11/dist-packages (from timm==1.0.12->autotrain-advanced) (0.21.0+cu124)
Requirement already satisfied: lightning-utilities>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from torchmetrics==1.6.0->autotrain-advanced) (0.14.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers==4.48.0->autotrain-advanced) (0.21.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from trl==0.13.0->autotrain-advanced) (13.9.4)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.11/dist-packages (from uvicorn==0.34.0->autotrain-advanced) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug==3.1.3->autotrain-advanced) (3.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost==2.1.3->autotrain-advanced) (2.21.5)
Requirement already satisfied: stringzilla>=3.10.4 in /usr/local/lib/python3.11/dist-packages (from albucore==0.0.21->albumentations==1.4.23->autotrain-advanced) (3.12.5)
Requirement already satisfied: simsimd>=5.9.2 in /usr/local/lib/python3.11/dist-packages (from albucore==0.0.21->albumentations==1.4.23->autotrain-advanced) (6.2.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (3.11.15)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna==4.1.0->autotrain-advanced) (1.1.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography==44.0.0->autotrain-advanced) (2.22)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets~=3.2.0->datasets[vision]~=3.2.0->autotrain-advanced) (1.20.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools==2.0.8->autotrain-advanced) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools==2.0.8->autotrain-advanced) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools==2.0.8->autotrain-advanced) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools==2.0.8->autotrain-advanced) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools==2.0.8->autotrain-advanced) (3.2.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna==4.1.0->autotrain-advanced) (3.2.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx==0.28.1->autotrain-advanced) (1.3.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.10.0->accelerate==1.2.1->autotrain-advanced) (12.3.1.170)

In [2]:
!pip install transformers datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.27.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.9.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [3]:
from google.colab import files
uploaded = files.upload()

Saving twittersentiment_1_1000_enriched.csv to twittersentiment_1_1000_enriched (1).csv

In [4]:
import pandas as pd
from datasets import Dataset

# Load CSV
df = pd.read_csv("/content/twittersentiment_1_1000_enriched.csv")

# Only keep relevant columns
df = df[["text", "Mistral_label"]]
df = df.dropna()

# Define label mapping
label_map = {
    "negative": 0,
    "positive": 2,
    "neutral": 1  # Include this if you have a 3-class problem
}

# Apply mapping
df["Mistral_label"] = df["Mistral_label"].map(label_map)

# Drop rows where label mapping failed
df = df.dropna(subset=["Mistral_label"])

# Convert to integer type
df["Mistral_label"] = df["Mistral_label"].astype(int)
df

                                                  text  Mistral_label
0        Sooo SAD I will miss you here in San Diego!!!              0
1                            my boss is bullying me...              2
2                       what interview! leave me alone              0
3     Sons of ****, why couldn`t they put them on t...              0
4    http://www.dothebouncy.com/smf - some shameles...              2
..                                                 ...            ...
993         I am twittering, LIKE A BOSS. Thanks Savvv              1
994   my sleep pattern is screwed i need to try and...              0
995   Since the demise of Woolworths it isn`t easy ...              0
996    may the fourth be with you! happy star wars day              2
997   I`ve been unlocked for decades now...just not...              2

[994 rows x 2 columns]

In [5]:
dataset = Dataset.from_pandas(df)
dataset

Dataset({
    features: ['text', 'Mistral_label', '__index_level_0__'],
    num_rows: 994
})

In [6]:
from transformers import AutoTokenizer

model_name = "FacebookAI/roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(example):
    return tokenizer(example["text"], padding="max_length", truncation=True)

tokenized_dataset = dataset.map(tokenize_function, batched=True)
tokenized_dataset = tokenized_dataset.rename_column("Mistral_label", "labels")
tokenized_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Map:   0%|          | 0/994 [00:00<?, ? examples/s]

In [7]:
tokenized_dataset

Dataset({
    features: ['text', 'labels', '__index_level_0__', 'input_ids', 'attention_mask'],
    num_rows: 994
})

In [24]:
import torch
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

# Optional: Confirm GPU is available
print("Using GPU:", torch.cuda.is_available())

# Load model with number of labels
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)

# Training arguments
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    push_to_hub=True,  # change to True if pushing after training
    hub_model_id="RajeevanL/Distill_Roberta",
    report_to="none"    # set to "wandb" or "tensorboard" if using logging
)

# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    eval_dataset=tokenized_dataset,  # use a validation split for better generalization
    tokenizer=tokenizer,
)

# Train
trainer.train()

Using GPU: True

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at FacebookAI/roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
<ipython-input-24-890314ac0601>:26: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

TrainOutput(global_step=189, training_loss=0.8287791877827316, metrics={'train_runtime': 166.2784, 'train_samples_per_second': 17.934, 'train_steps_per_second': 1.137, 'total_flos': 784604211664896.0, 'train_loss': 0.8287791877827316, 'epoch': 3.0})

In [9]:
# !pip install huggingface_hub --upgrade
from huggingface_hub import HfApi, login

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (0.27.0)
Collecting huggingface_hub
  Using cached huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2024.9.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2025.1.31)
Using cached huggingface_hub-0.30.2-py3-none-any.whl (481 kB)
Installing collected packages: huggingface_hub
  Attempting uninstall: huggingface_hub
    Found existing installation: huggingface-hub 0.27.0
    Uninstalling huggingface-hub-0.27.0:
      Successfully uninstalled huggingface-hub-0.27.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autotrain-advanced 0.8.36 requires huggingface-hub==0.27.0, but you have huggingface-hub 0.30.2 which is incompatible.
Successfully installed huggingface_hub-0.30.2

In [ ]:
login("token")